### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by HeadClot** [AssemblyJohn/Critias-FoliageSystem#1]
Hey would it be possible to add a license to this?

MIT or similar would be preferred :)

**Comment by woroko** [comment]
This would be nice, because there is no way to buy this asset any more. Adding a license or alternatively releasing this again on the Asset Store would fix this. Currently, there is no way to use the code safely without a license.

**Comment by AssemblyJohn** [comment]
Hello,

I would certainly add a license, I've just forgot to add one.
